import type { DocumentRow, SubmissionForm } from './types';

export const SUBMISSION_FORMS: SubmissionForm[] = [
  {
    id: 'general',
    name: 'General',
    group: 'Supplier assessment',
    status: 'submitted',
    lastEdited: 'Last edited 10 Jun by Peter Kaminsky',
    questions: [
      {
        id: 'org-name',
        label: "1. What is your organisation's registered name",
        required: true,
        kind: 'text',
        value: 'The Rocket Science Group, LLC',
      },
      {
        id: 'org-country',
        label: '2. Which country is your organisation in',
        required: true,
        kind: 'select',
        value: 'United States',
      },
      {
        id: 'org-address',
        label: '3. What is your organisations head office address',
        required: true,
        kind: 'text',
        fields: [
          { label: 'Address line', value: 'The Rocket Science Group, LLC\n675 Ponce de Leon Ave NE\nSuite 5000' },
          { label: 'City', value: 'Atlanta' },
          { label: 'State', value: 'GA', halfWidth: true },
          { label: 'Postcode', value: '30308', halfWidth: true },
        ],
      },
      {
        id: 'main-contact',
        label: '4. Please add in the main contact point',
        required: true,
        kind: 'text',
        fields: [
          { label: 'Full name', value: 'Peter Kaminsky' },
          { label: 'Position', value: 'Account manager' },
          { label: 'Email address', value: 'peter.k@mailchimp.co' },
          { label: 'Phone number (Optional)', value: '' },
        ],
      },
    ],
  },
  {
    id: 'legal',
    name: 'Legal',
    group: 'Supplier assessment',
    status: 'submitted',
    lastEdited: 'Last edited 10 Jun by Peter Kaminsky',
    questions: [
      {
        id: 'legal-entity',
        label: '1. Which legal entity will hold the contract',
        required: true,
        kind: 'text',
        value: 'The Rocket Science Group, LLC (Delaware)',
      },
      {
        id: 'legal-terms',
        label: '2. Which contracting paper do you propose',
        required: true,
        kind: 'select',
        value: 'Supplier MSA with ACME data protection addendum',
      },
      {
        id: 'legal-retention',
        label: '3. What is your standard data retention window after termination',
        required: true,
        kind: 'text',
        value: '90 days, reducible to 30 days on written request',
      },
      {
        id: 'legal-insurance',
        label: '4. Insurance cover held',
        required: true,
        kind: 'text',
        fields: [
          { label: 'Professional indemnity', value: '$10,000,000' },
          { label: 'Cyber liability', value: '$5,000,000' },
        ],
      },
    ],
  },
  {
    id: 'security',
    name: 'Security',
    group: 'Supplier assessment',
    status: 'submitted',
    lastEdited: 'Last edited 10 Sep by Peter Kaminsky',
    flags: [
      {
        id: 'flag-sec-1',
        questionId: 'sec-certs',
        raisedById: 'sadie',
        raisedAt: '11 Sep',
        reason: 'SOC 2 report is from Nov 2023 — outside our 12 month window. Ask for the current period report.',
        severity: 'blocker',
      },
      {
        id: 'flag-sec-2',
        questionId: 'sec-pen',
        raisedById: 'sadie',
        raisedAt: '11 Sep',
        reason: 'Last penetration test was over 24 months ago. Policy requires one within the last 12 months.',
        severity: 'blocker',
      },
      {
        id: 'flag-sec-3',
        questionId: 'sec-pen',
        raisedById: 'sam',
        raisedAt: '12 Sep',
        reason: 'No remediation evidence attached for the findings of that test.',
        severity: 'query',
      },
      {
        id: 'flag-sec-4',
        questionId: 'sec-subprocessors',
        raisedById: 'amir',
        raisedAt: '12 Sep',
        reason: 'All three sub-processors are US hosted. Confirm the transfer mechanism for EU personal data.',
        severity: 'query',
      },
    ],
    questions: [
      {
        id: 'sec-certs',
        label: '1. Which certifications do you currently hold',
        required: true,
        kind: 'text',
        value: 'SOC 2 Type 2 (Nov 2023), ISO 27001:2022',
      },
      {
        id: 'sec-pen',
        label: '2. When was your last external penetration test',
        required: true,
        kind: 'select',
        value: '24 months +',
      },
      {
        id: 'sec-subprocessors',
        label: '3. List sub-processors with access to customer data',
        required: true,
        kind: 'text',
        value: 'Amazon Web Services (US), Twilio SendGrid (US), Snowflake (US)',
      },
    ],
  },
  {
    id: 'business-continuity',
    name: 'Business continuity',
    group: 'Supplier assessment',
    status: 'submitted',
    lastEdited: 'Last edited 8 Sep by Peter Kaminsky',
    questions: [
      {
        id: 'bc-rto',
        label: '1. What is your recovery time objective',
        required: true,
        kind: 'select',
        value: '4 hours',
      },
      {
        id: 'bc-test',
        label: '2. When was your continuity plan last tested',
        required: true,
        kind: 'text',
        value: 'March 2024 — full failover exercise, us-east-1 to us-west-2',
      },
    ],
  },
  {
    id: 'incident-management',
    name: 'Incident management',
    group: 'Supplier assessment',
    status: 'submitted',
    lastEdited: 'Last edited 9 Sep by Peter Kaminsky',
    flags: [
      {
        id: 'flag-im-1',
        questionId: 'im-notify',
        raisedById: 'amir',
        raisedAt: '10 Sep',
        reason: '72 hours does not meet our 24 hour contractual notification requirement.',
        severity: 'blocker',
      },
      {
        id: 'flag-im-2',
        questionId: 'im-history',
        raisedById: 'sadie',
        raisedAt: '10 Sep',
        reason: 'Post-incident review is referenced but was not attached to the submission.',
        severity: 'query',
      },
    ],
    questions: [
      {
        id: 'im-notify',
        label: '1. Breach notification window',
        required: true,
        kind: 'select',
        value: 'Within 72 hours',
      },
      {
        id: 'im-history',
        label: '2. Reportable incidents in the last 24 months',
        required: true,
        kind: 'text',
        value: 'One — March 2023, third party email relay misconfiguration. Post-incident review attached.',
      },
    ],
  },
  {
    id: 'engagement-general',
    name: 'General',
    group: 'Engagement',
    status: 'pending',
    questions: [],
  },
  {
    id: 'engagement-financial',
    name: 'Financial details & PO',
    group: 'Engagement',
    status: 'pending',
    questions: [],
  },
  {
    id: 'engagement-contacts',
    name: 'Key contacts',
    group: 'Engagement',
    status: 'pending',
    questions: [],
  },
];

export const INITIAL_DOCUMENTS: DocumentRow[] = [
  {
    id: 'doc-1',
    name: 'Mailchimp - SOC2.pdf',
    storeInRepository: true,
    type: 'SOC2',
    source: 'Form: Compliance',
    uploadedById: 'john',
    uploadedAt: '22 Apr 12:34',
  },
  {
    id: 'doc-2',
    name: 'Mailchimp - Contract-v3.pdf',
    storeInRepository: true,
    type: 'Contract',
    source: 'Form: Legal',
    uploadedById: 'john',
    uploadedAt: '22 Apr 16:56',
  },
  {
    id: 'doc-3',
    name: 'Mailchimp - Contract-v2.pdf',
    storeInRepository: false,
    type: 'Contract',
    source: 'Manual upload',
    uploadedById: 'john',
    uploadedAt: '22 Apr 16:56',
  },
  {
    id: 'doc-4',
    name: 'Mailchimp - Contract-v1.pdf',
    storeInRepository: false,
    source: 'Form: Legal',
    uploadedById: 'john',
    uploadedAt: '22 Apr 16:56',
  },
];

